tasks:
  - init: sh ./scripts/setup.sh

vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - matklad.rust-analyzer
    - donjayamanne.git-extension-pack
